### ISSUE TITLE
drbd-dkms needed packages

### ISSUE THREAD

**Issue by zeventh** [LINBIT/drbdmanage-proxmox#1]
When installing drbd-dkms it installs common linux-headers but what is needed to be able to compile is the pve-headers package for your running kernel version.

**Comment by rck** [comment]
True. I guess that was unnoticed so far because if these headers are installed, dkms builds binary modules for them anyways. Still, we should switch that for Proxmox dkms builds. Should not be too difficult.

**Comment by rck** [comment]
Okay, I checked some existing Debian packages and none of them has a dependency on the header files. Usually they state it in the description:

aufs-dkms:
To install this package, you have to install the header files for your current kernel manually (usually included in the "linux-headers-<your architecture>").

virtualbox-dkms:
This package provides the source code for the virtualbox kernel module to be build with dkms. Kernel sources or headers are required to compile this  module.

So from a packaging point of view we already do the correct thing here (not mentioning any headers at all). My best guess why the standard headers are installed is because "dkms" itself recommends them.
